sudo: required
services: 
  - docker

before_install:
  - docker build -t devtest -f Dockerfile.dev .

script:
  - docker run -e CI=true devtest npm run test

deploy: 
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "devops_intro"
  env: "DevopsIntro-env"
  bucket_name: "elasticbeanstalk-eu-central-1-876154484610"
  bucket_path: "devops_intro"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY