version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    ports: 
      - "8420:3000"
  
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    ports:
      - "8420:3000"
    command: ["npm", "run", "test"]      